version: '3.8'

services:
  # FastAPI Backend
  gym-pro-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym-pro-rag-api
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - DEBUG=false
    env_file:
      - .env
    volumes:
      # Mount data directory if you want to update gym data without rebuilding
      - ./data:/app/data:ro
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gym-pro-network

  # Streamlit Frontend
  gym-pro-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: gym-pro-streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://gym-pro-api:8001
    depends_on:
      - gym-pro-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gym-pro-network

networks:
  gym-pro-network:
    driver: bridge

volumes:
  gym_pro_logs:
    driver: local
